PHGCUT – Flex_extract: Calculation of etadot
PHGCUT Subroutine
32 statements
Source File
public subroutine PHGCUT(CXMN, FELD, WSAVE, IFAX, Z, MNAUF, MMAX, MAUF, MANF, MAXL, MAXB, MLEVEL)
Carries out the transformation of a field variable from the phase space into the physical space on spherical coordinates. It is possible to specify a section of the Earth. This subroutine is slower thatn PHGRPH.
Arguments
Type Intent Optional Attributes Name
real :: CXMN
real :: FELD(MAXL,MAXB,MLEVEL)
real :: WSAVE
integer :: IFAX(10)
real :: Z(0:((MMAX+3)*(MMAX+4))/2,MAXB)
integer :: MNAUF
integer :: MMAX
integer :: MAUF
integer :: MANF
integer :: MAXL
integer :: MAXB
integer :: MLEVEL
Calls
Called by
Contents
None
Call graph
phgcut calls phsymcut, phgpns
phsymcut calls rfourtr
phgpns calls rfourtr
rfourtr calls fft99
calc_etadot calls phgcut