READLATLON – Flex_extract: Calculation of etadot
READLATLON Subroutine
55 statements
Source File
public subroutine READLATLON(filename, feld, maxl, maxb, mlevel, mpar)
Uses
GRIB_API
Read a field from GRIB file on lat-lon grid
Arguments
Type Intent Optional Attributes Name
character(len=*) :: filename
real, dimension(maxl,maxb,mlevel) :: feld
integer :: maxl
integer :: maxb
integer :: mlevel
integer :: mpar(:)
Calls
Called by
Contents
None
Call graph
readlatlon calls grib_count_in_file, grib_close_file
calc_etadot calls readlatlon