RFOURTR – Flex_extract: Calculation of etadot
RFOURTR Subroutine
15 statements
Source File
public subroutine RFOURTR(CXM, TRIGS, IFAX, MNAUF, MAXL, ISIGN)
Calculates the Fourier sum with an FFT algorithm
Arguments
Type Intent Optional Attributes Name
real :: CXM
real :: TRIGS(2*MAXL)
integer :: IFAX(10)
integer :: MNAUF
integer :: MAXL
integer :: ISIGN
Calls
Called by
Contents
None
Call graph
rfourtr calls fft99
phsymcut calls rfourtr
phgpns calls rfourtr
phgracut calls rfourtr
phgcut calls phsymcut, phgpns
calc_etadot calls phgcut